# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- script: |
    ls
    echo '$(System.DefaultWorkingDirectory)'
  displayName: 'ls'

- script: |
    npm install
  displayName: 'npm install'

- script: ls
  displayName: 'npm test'
  workingDirectory: '../tests/products.test.js'

